spring:
  profiles:
    active: prd
  application:
    name: web-test

server:
  port: 8088

nebula:
  web:
    response-code: 200
    monitor-open: true
    monitor:
      type: feishu
    monitor-url: https://open.feishu.cn/open-apis/bot/v2/hook/xxxxx
    