spring:
  profiles:
    active: test
  application:
    name: web-test



#  datasource:
#    driverClassName: org.h2.Driver
#    password: password
#    url: jdbc:h2:mem:testdb
#    username: sa
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

server:
  port: 8088

db:
  nebula:
    pg:
      write:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:write;MODE=PostgreSQL
        username: sa

      read:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:read;MODE=PostgreSQL
        username: sa


