/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
package com.nebula.web.boot.api;

import static org.assertj.core.api.Assertions.assertThat;

import com.nebula.web.boot.annotation.NebulaMessageKey;
import com.nebula.web.boot.enums.ResultCode;
import com.nebula.web.common.utils.SpringBeanUtils;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * 无 Spring 上下文（未装配 MessageSource）时，消息 key 兜底返回默认 message。
 */
class NebulaResponseI18nFallbackTest {
    
    @BeforeAll
    static void setUp() {
        new SpringBeanUtils().setApplicationContext(null);
        NebulaResponse.resetCodeResolverForTest();
    }
    
    @Test
    void fallsBackToDefaultMessageWithoutMessageSource() {
        NebulaResponse<Void> response = NebulaResponse.fail(ResultCode.PARAM_MISS);
        assertThat(response.getMsg()).isEqualTo(ResultCode.PARAM_MISS.getMessage());
    }
    
    @Test
    void translateWithoutMessageSourceReturnsDefault() {
        assertThat(NebulaResponse.translate(ResultCode.PARAM_MISS.resolveMessageKey(), null, "缺少必要的请求参数"))
                .isEqualTo("缺少必要的请求参数");
    }
    
    @Test
    void messageKeyAutoGeneratedFromClassNameAndConstant() {
        assertThat(ResultCode.PARAM_MISS.resolveMessageKey()).isEqualTo("result_code.param_miss");
        assertThat(ResultCode.INTERNAL_SERVER_ERROR.resolveMessageKey())
                .isEqualTo("result_code.internal_server_error");
        assertThat(ResultCode.PARAM_BIND_ERROR.resolveMessageKey()).isEqualTo("result_code.param_bind_error");
    }
    
    @Test
    void annotationKeyOverridesAutoGenerated() {
        assertThat(AnnotatedCode.ORDER_NOT_FOUND.resolveMessageKey()).isEqualTo("order.not_found");
        assertThat(AnnotatedCode.STOCK_NOT_ENOUGH.resolveMessageKey())
                .isEqualTo("annotated_code.stock_not_enough");
    }
    
    @Getter
    @AllArgsConstructor
    private enum AnnotatedCode implements IErrorCode {
        
        @NebulaMessageKey("order.not_found")
        ORDER_NOT_FOUND(40001, "订单不存在"),
        
        STOCK_NOT_ENOUGH(40002, "库存不足");
        
        private final int code;
        
        private final String message;
        
    }
    
}
