apiVersion: v1
kind: Service
metadata:
  name: ${rootArtifactId}
  labels:
    app: ${rootArtifactId}
spec:
  type: ClusterIP
  selector:
    app: ${rootArtifactId}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
