<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.weihubeats</groupId>
        <artifactId>spring-boot-nebula</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>spring-boot-nebula-samples</artifactId>
    <packaging>pom</packaging>
    <name>spring-boot-nebula-samples</name>

    <modules>
        <module>spring-boot-nebula-web-sample</module>
        <module>spring-boot-nebula-distribute-lock-sample</module>
        <module>spring-boot-nebula-mybatis-sample</module>
        <module>spring-boot-nebula-excel-sample</module>
        <module>spring-boot-nebula-dynamic-datasource-sample</module>
        <module>spring-boot-nebula-join-sample</module>
        <module>spring-boot-nebula-logback-sample</module>
        <module>spring-boot-nebula-feign-sample</module>
        <module>spring-boot-nebula-i18n-sample</module>
    </modules>

    <properties>
        <skipPublishing>true</skipPublishing>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <configuration>
                    <skipPublishing>true</skipPublishing>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
